server.port=9001

spring.application.name=langchain4j-01helloworld

# https://bailian.console.aliyun.com/cn-beijing/?tab=model#/model-market/detail/qwen3.5-plus
langchain4j.open-ai.chat-model.api-key=your-api-key
langchain4j.open-ai.chat-model.model-name=qwen3.5-plus
langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
